// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: proto/metrics.proto

package grpcmetrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric_Type int32

const (
	Metric_UNSPECIFIED Metric_Type = 0
	Metric_COUNTER     Metric_Type = 1
	Metric_GAUGE       Metric_Type = 2
)

// Enum value maps for Metric_Type.
var (
	Metric_Type_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "COUNTER",
		2: "GAUGE",
	}
	Metric_Type_value = map[string]int32{
		"UNSPECIFIED": 0,
		"COUNTER":     1,
		"GAUGE":       2,
	}
)

func (x Metric_Type) Enum() *Metric_Type {
	p := new(Metric_Type)
	*p = x
	return p
}

func (x Metric_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metrics_proto_enumTypes[0].Descriptor()
}

func (Metric_Type) Type() protoreflect.EnumType {
	return &file_proto_metrics_proto_enumTypes[0]
}

func (x Metric_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_Type.Descriptor instead.
func (Metric_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{0, 0}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // имя метрики
	Type          Metric_Type            `protobuf:"varint,2,opt,name=type,proto3,enum=grpcmetrics.Metric_Type" json:"type,omitempty"` // тип метрики
	Counter       int64                  `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"`
	Gauge         float64                `protobuf:"fixed64,4,opt,name=gauge,proto3" json:"gauge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetType() Metric_Type {
	if x != nil {
		return x.Type
	}
	return Metric_UNSPECIFIED
}

func (x *Metric) GetCounter() int64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *Metric) GetGauge() float64 {
	if x != nil {
		return x.Gauge
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Metric                `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetValue() *Metric {
	if x != nil {
		return x.Value
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Metric                `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetValue() *Metric {
	if x != nil {
		return x.Value
	}
	return nil
}

type MultiUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Metric              `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiUpdate) Reset() {
	*x = MultiUpdate{}
	mi := &file_proto_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiUpdate) ProtoMessage() {}

func (x *MultiUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiUpdate.ProtoReflect.Descriptor instead.
func (*MultiUpdate) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *MultiUpdate) GetValues() []*Metric {
	if x != nil {
		return x.Values
	}
	return nil
}

type RequestMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMetrics) Reset() {
	*x = RequestMetrics{}
	mi := &file_proto_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetrics) ProtoMessage() {}

func (x *RequestMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetrics.ProtoReflect.Descriptor instead.
func (*RequestMetrics) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{4}
}

type MultiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Metric              `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiResponse) Reset() {
	*x = MultiResponse{}
	mi := &file_proto_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiResponse) ProtoMessage() {}

func (x *MultiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiResponse.ProtoReflect.Descriptor instead.
func (*MultiResponse) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *MultiResponse) GetValues() []*Metric {
	if x != nil {
		return x.Values
	}
	return nil
}

type RequestPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPing) Reset() {
	*x = RequestPing{}
	mi := &file_proto_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPing) ProtoMessage() {}

func (x *RequestPing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPing.ProtoReflect.Descriptor instead.
func (*RequestPing) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{6}
}

type ResposePing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResposePing) Reset() {
	*x = ResposePing{}
	mi := &file_proto_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResposePing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResposePing) ProtoMessage() {}

func (x *ResposePing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResposePing.ProtoReflect.Descriptor instead.
func (*ResposePing) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{7}
}

var File_proto_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x13proto/metrics.proto\x12\vgrpcmetrics\"\xab\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.grpcmetrics.Metric.TypeR\x04type\x12\x18\n" +
	"\acounter\x18\x03 \x01(\x03R\acounter\x12\x14\n" +
	"\x05gauge\x18\x04 \x01(\x01R\x05gauge\"/\n" +
	"\x04Type\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x01\x12\t\n" +
	"\x05GAUGE\x10\x02\"5\n" +
	"\bResponse\x12)\n" +
	"\x05value\x18\x01 \x01(\v2\x13.grpcmetrics.MetricR\x05value\"4\n" +
	"\aRequest\x12)\n" +
	"\x05value\x18\x01 \x01(\v2\x13.grpcmetrics.MetricR\x05value\":\n" +
	"\vMultiUpdate\x12+\n" +
	"\x06values\x18\x01 \x03(\v2\x13.grpcmetrics.MetricR\x06values\"\x10\n" +
	"\x0eRequestMetrics\"<\n" +
	"\rMultiResponse\x12+\n" +
	"\x06values\x18\x01 \x03(\v2\x13.grpcmetrics.MetricR\x06values\"\r\n" +
	"\vRequestPing\"\r\n" +
	"\vResposePing2\x9a\x02\n" +
	"\x12StreamMultiService\x12<\n" +
	"\rUpdateRequest\x12\x14.grpcmetrics.Request\x1a\x15.grpcmetrics.Response\x12J\n" +
	"\x12MultiUpdateRequest\x12\x18.grpcmetrics.MultiUpdate\x1a\x1a.grpcmetrics.MultiResponse\x128\n" +
	"\tGetMetric\x12\x14.grpcmetrics.Request\x1a\x15.grpcmetrics.Response\x12@\n" +
	"\n" +
	"GetMetrics\x12\x1b.grpcmetrics.RequestMetrics\x1a\x13.grpcmetrics.Metric0\x01B<Z:github.com/4aleksei/metricscum/internal/common/grpcmetricsb\x06proto3"

var (
	file_proto_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_proto_rawDescData []byte
)

func file_proto_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_proto_rawDescData
}

var file_proto_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_metrics_proto_goTypes = []any{
	(Metric_Type)(0),       // 0: grpcmetrics.Metric.Type
	(*Metric)(nil),         // 1: grpcmetrics.Metric
	(*Response)(nil),       // 2: grpcmetrics.Response
	(*Request)(nil),        // 3: grpcmetrics.Request
	(*MultiUpdate)(nil),    // 4: grpcmetrics.MultiUpdate
	(*RequestMetrics)(nil), // 5: grpcmetrics.RequestMetrics
	(*MultiResponse)(nil),  // 6: grpcmetrics.MultiResponse
	(*RequestPing)(nil),    // 7: grpcmetrics.RequestPing
	(*ResposePing)(nil),    // 8: grpcmetrics.ResposePing
}
var file_proto_metrics_proto_depIdxs = []int32{
	0, // 0: grpcmetrics.Metric.type:type_name -> grpcmetrics.Metric.Type
	1, // 1: grpcmetrics.Response.value:type_name -> grpcmetrics.Metric
	1, // 2: grpcmetrics.Request.value:type_name -> grpcmetrics.Metric
	1, // 3: grpcmetrics.MultiUpdate.values:type_name -> grpcmetrics.Metric
	1, // 4: grpcmetrics.MultiResponse.values:type_name -> grpcmetrics.Metric
	3, // 5: grpcmetrics.StreamMultiService.UpdateRequest:input_type -> grpcmetrics.Request
	4, // 6: grpcmetrics.StreamMultiService.MultiUpdateRequest:input_type -> grpcmetrics.MultiUpdate
	3, // 7: grpcmetrics.StreamMultiService.GetMetric:input_type -> grpcmetrics.Request
	5, // 8: grpcmetrics.StreamMultiService.GetMetrics:input_type -> grpcmetrics.RequestMetrics
	2, // 9: grpcmetrics.StreamMultiService.UpdateRequest:output_type -> grpcmetrics.Response
	6, // 10: grpcmetrics.StreamMultiService.MultiUpdateRequest:output_type -> grpcmetrics.MultiResponse
	2, // 11: grpcmetrics.StreamMultiService.GetMetric:output_type -> grpcmetrics.Response
	1, // 12: grpcmetrics.StreamMultiService.GetMetrics:output_type -> grpcmetrics.Metric
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_metrics_proto_init() }
func file_proto_metrics_proto_init() {
	if File_proto_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_proto_depIdxs,
		EnumInfos:         file_proto_metrics_proto_enumTypes,
		MessageInfos:      file_proto_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_proto = out.File
	file_proto_metrics_proto_goTypes = nil
	file_proto_metrics_proto_depIdxs = nil
}
